/* eslint-disable @next/next/no-img-element */
/* eslint-disable @next/next/no-html-link-for-pages */

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { RootProvider } from "fumadocs-ui/provider";
import { SVGProps } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-[family-name:var(--font-geist-sans)] bg-zinc-950 text-zinc-100
          flex flex-col min-h-screen items-stretch overflow-x-hidden
          `}
      >
        <RootProvider>
          <header className="px-8 sticky top-0 bg-zinc-950 z-10">
            <div className="max-w-6xl mx-auto flex items-center justify-between h-14 relative ">
              <div className=" flex items-center gap-6 text-sm font-medium">
                <a
                  href="/"
                  className="text-xl font-semibold flex gap-2 tracking-tighter"
                >
                  <img
                    src="https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f510.svg"
                    width="16"
                    height="16"
                    alt=""
                    className="block"
                  />
                  <div>Doobie.js</div>
                </a>
              </div>
              <div className="flex gap-6 text-sm items-center">
                <a
                  href="/demo"
                  className="opacity-70 hover:opacity-90 cursor-pointer"
                >
                  <div>Demo</div>
                </a>
                <a
                  href="/docs"
                  className="opacity-70 hover:opacity-90 cursor-pointer"
                >
                  <div>Guide</div>
                </a>
                <a
                  href="/"
                  className="opacity-70 hover:opacity-90 cursor-pointer text-2xl">
                  <MdiGithub />
                </a>
              </div>

            </div>
          </header>
          <div className="min-h-[calc(100vh_-_4rem)] mx-auto flex flex-col items-center w-full">
            {children}
          </div>
        </RootProvider>
      </body>
    </html>
  );
}

function MdiGithub(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="1em"
      height="1em"
      viewBox="0 0 24 24"
      {...props}
    >
      <path
        fill="currentColor"
        d="M12 2A10 10 0 0 0 2 12c0 4.42 2.87 8.17 6.84 9.5c.5.08.66-.23.66-.5v-1.69c-2.77.6-3.36-1.34-3.36-1.34c-.46-1.16-1.11-1.47-1.11-1.47c-.91-.62.07-.6.07-.6c1 .07 1.53 1.03 1.53 1.03c.87 1.52 2.34 1.07 2.91.83c.09-.65.35-1.09.63-1.34c-2.22-.25-4.55-1.11-4.55-4.92c0-1.11.38-2 1.03-2.71c-.1-.25-.45-1.29.1-2.64c0 0 .84-.27 2.75 1.02c.79-.22 1.65-.33 2.5-.33s1.71.11 2.5.33c1.91-1.29 2.75-1.02 2.75-1.02c.55 1.35.2 2.39.1 2.64c.65.71 1.03 1.6 1.03 2.71c0 3.82-2.34 4.66-4.57 4.91c.36.31.69.92.69 1.85V21c0 .27.16.59.67.5C19.14 20.16 22 16.42 22 12A10 10 0 0 0 12 2"
      ></path>
    </svg>
  );
}
